// ReSharper disable All
namespace FF7R2.Constants;

public static class BattleSummonConditionsProperties {
    public const string AppearPointIDInAir = "AppearPointIDInAir";
    public const string AppearPointIDInGround = "AppearPointIDInGround";
    public const string CallMaximumNumber = "CallMaximumNumber";
    public const string CutSceneAreaSizeID = "CutSceneAreaSizeID";
    public const string CutScenePointID = "CutScenePointID";
    public const string EnableCallSummon00 = "EnableCallSummon00";
    public const string EnableCallSummon01 = "EnableCallSummon01";
    public const string EnableCallSummon02 = "EnableCallSummon02";
    public const string EnableCallSummon03 = "EnableCallSummon03";
    public const string EnableCallSummon04 = "EnableCallSummon04";
    public const string EnableCallSummon05 = "EnableCallSummon05";
    public const string EnableCallSummon06 = "EnableCallSummon06";
    public const string EnableCallSummon07 = "EnableCallSummon07";
    public const string EnableCallSummon08 = "EnableCallSummon08";
    public const string EnableCallSummon09 = "EnableCallSummon09";
    public const string EnableCallSummon10 = "EnableCallSummon10";
    public const string EnableCallSummon11 = "EnableCallSummon11";
    public const string EnableCallSummon12 = "EnableCallSummon12";
    public const string EnableCallSummon13 = "EnableCallSummon13";
    public const string EnableCallSummon14 = "EnableCallSummon14";
    public const string EnableCallSummon15 = "EnableCallSummon15";
    public const string EnableCallSummon16 = "EnableCallSummon16";
    public const string EnableCallSummon17 = "EnableCallSummon17";
    public const string EnableCallSummon18 = "EnableCallSummon18";
    public const string EnableCallSummon19 = "EnableCallSummon19";
    public const string EnableCallSummonBitField = "EnableCallSummonBitField";
    public const string EnvSetOffID_Array = "EnvSetOffID_Array";
    public const string EnvSetOnID_Array = "EnvSetOnID_Array";
    public const string InvalidAreaSize = "InvalidAreaSize";
    public const string Number = "Number";
    public const string Phase01 = "Phase01";
    public const string Phase02 = "Phase02";
    public const string Phase03 = "Phase03";
    public const string Phase04 = "Phase04";
    public const string Phase05 = "Phase05";
    public const string Phase06 = "Phase06";
    public const string Phase07 = "Phase07";
    public const string Phase08 = "Phase08";
    public const string PhaseBitField = "PhaseBitField";
    public const string StartCallValueSizeType = "StartCallValueSizeType";
    public const string SummonCoefficient = "SummonCoefficient";
    public const string SummonCorrection = "SummonCorrection";
    public const string Trigger01 = "Trigger01";
    public const string Trigger02 = "Trigger02";
    public const string Trigger03 = "Trigger03";
    public const string Trigger04 = "Trigger04";
    public const string Trigger05 = "Trigger05";
    public const string TriggerBitField = "TriggerBitField";
}
