// ReSharper disable All
namespace FF7R2.Constants;

public static class MateriaProperties {
    public const string EffectDescription_Array = "EffectDescription_Array";
    public const string LevelUpItemID_Array = "LevelUpItemID_Array";
    public const string SummonMateriaLevelUpFlagID_Array = "SummonMateriaLevelUpFlagID_Array";
    public const string EffectString_Array = "EffectString_Array";
    public const string EffectType_Array = "EffectType_Array";
    public const string ExpNextLv_Array = "ExpNextLv_Array";
    public const string SaleValueLv_Array = "SaleValueLv_Array";
    public const string EffectValue_Array = "EffectValue_Array";
    public const string MateriaDetailLabel = "MateriaDetailLabel";
    public const string MovieName = "MovieName";
    public const string BattleCharaSpecID = "BattleCharaSpecID";
    public const string CharaSpecID = "CharaSpecID";
    public const string AddAttributeFlag = "AddAttributeFlag";
    public const string AddStatusChangeFlag = "AddStatusChangeFlag";
    public const string LinkDestFlag = "LinkDestFlag";
    public const string AttackAdd = "AttackAdd";
    public const string AttackScale = "AttackScale";
    public const string MagicAttackAdd = "MagicAttackAdd";
    public const string MagicAttackScale = "MagicAttackScale";
    public const string DefenseAdd = "DefenseAdd";
    public const string DefenseScale = "DefenseScale";
    public const string MagicDefenseAdd = "MagicDefenseAdd";
    public const string MagicDefenseScale = "MagicDefenseScale";
    public const string StrengthAdd = "StrengthAdd";
    public const string StrengthScale = "StrengthScale";
    public const string MagicAdd = "MagicAdd";
    public const string MagicScale = "MagicScale";
    public const string VitalityAdd = "VitalityAdd";
    public const string VitalityScale = "VitalityScale";
    public const string SpiritAdd = "SpiritAdd";
    public const string SpiritScale = "SpiritScale";
    public const string LuckAdd = "LuckAdd";
    public const string LuckScale = "LuckScale";
    public const string DexterityAdd = "DexterityAdd";
    public const string DexterityScale = "DexterityScale";
    public const string HPMaxAdd = "HPMaxAdd";
    public const string HPMaxScale = "HPMaxScale";
    public const string MPMaxAdd = "MPMaxAdd";
    public const string MPMaxScale = "MPMaxScale";
    public const string CriticalHitRateAdd = "CriticalHitRateAdd";
    public const string CriticalHitRateScale = "CriticalHitRateScale";
    public const string LinkSrcFlag = "LinkSrcFlag";
    public const string AddSpecialEffectFlag = "AddSpecialEffectFlag";
    public const string LvMax = "LvMax";
    public const string EffectEnableTypeDisplay = "EffectEnableTypeDisplay";
    public const string EffectEnableType = "EffectEnableType";
    public const string LevelUpType = "LevelUpType";
    public const string StatusChangeProbability = "StatusChangeProbability";
    public const string MateriaType = "MateriaType";
}
